/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NeonDatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
